[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
fuzz = { runs = 10_000 }
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'create3-factory/=lib/create3-factory/'
]
solc = '0.8.24'

[profile.ci]
fuzz = { runs = 1_000 }
verbosity = 4

[etherscan]
abstract = { key = "${ETHERSCAN_KEY}" }
arbitrum = { key = "${ETHERSCAN_KEY}" }
base = { key = "${ETHERSCAN_KEY}" }
linea = { key = "${ETHERSCAN_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
