[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
fuzz = { runs = 10_000 }
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/'
]
solc = '0.8.24'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
